general.import = ["current-theme.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 14

[window]
dimensions = { columns = 180, lines = 54 }
padding.x = 14
padding.y = 10
decorations = "Full"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[terminal]
shell = { program = "/bin/zsh" }

[mouse]
hide_when_typing = true
