[general]
import = ["~/.current-theme.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14

[window]
dimensions = { columns = 180, lines = 48 }
padding.x = 14
padding.y = 10
decorations = "Full"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[terminal]
shell = { program = "/bin/zsh" }

[mouse]
hide_when_typing = true
